trigger:
- main  # Adjust to your branch name if necessary

pool:
  vmImage: 'windows-latest'  # Use a Windows-based agent for .NET builds

stages:
- stage: "Build"
  displayName: 'Build and Publish Artifact'
  jobs:
  - job: 'BuildAndPublish'
    displayName: 'Build .NET framework'
    steps:
    # Step 1: Install NuGet packages
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
      displayName: 'Restore NuGet Packages'

    # Step 2: Build the application
    - task: VSBuild@1
      inputs:
        solution: '**/*.sln'  # Adjust to your solution file path
        msbuildArgs: '/p:TargetFrameworkVersion=v4.5 /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: 'Any CPU'
        configuration: 'Release'
      displayName: 'Build Solution with .NET Framework 4.5'

    # Step 3: Publish build artifact
    - task: PublishPipelineArtifact@1
      inputs:
        pathToPublish: '$(Pipeline.Workspace)'  # Folder containing the build output
        artifactName: 'myartifact'  # Name of the published artifact
        publishLocation: 'pipeline'
      displayName: 'Publish Build Artifact'
